# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trivago/logging/Header.proto

begin; require 'google/protobuf'; rescue LoadError; end

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "ProtoHeader" do
    optional :unix_timestamp, :int64, 1
    optional :sender_id, :string, 2
  end
end


ProtoHeader = Google::Protobuf::DescriptorPool.generated_pool.lookup("ProtoHeader").msgclass
